---
abstract: 'A tools provide few useful MediaWiki operation'
author:
  - 'Natal Ngétal'
build_requires:
  Module::Build: 0.3601
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.009, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MediaWikiUtils
requires:
  Carp: 0
  LWP::UserAgent: 0
  MediaWiki::API: 0
  Moo: 0
  MooX::Cmd: 0
  MooX::Options: 0
  Text::Unaccent::PurePerl: 0
  Types::Standard: 0
  pQuery: 0
  strict: 0
  warnings: 0
version: 0.141010
